name: "Cairn"
description: "❇️ | Self-hosted uptime monitoring with incident management and status pages"
version: "1.0.1.1"
slug: "cairn"
url: "https://github.com/TRC-Loop/cairn"
startup: services
boot: auto
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - armhf

persist: true
map:
  - data:rw

ingress: true
ingress_port: 8080
panel_icon: "mdi:list-status"
panel_title: "Cairn"

ports:
  8080/tcp: 3002

hassio_api: true

options:
  CAIRN_ENCRYPTION_KEY: "ChangeMe_32_Chars_Minimum"
  log_level: info
schema:
  CAIRN_ENCRYPTION_KEY: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
